sidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pengguna.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('trigger3/',include('trigger3.urls'))
]

trigger3/urls.py
from django.urls import path

from . import views

app_name = 'trigger3'

urlpatterns = [
    path('createpesanansumberdaya', views.createPesananSD, name='CreatePesananSumberDaya'),
    path('readpesanansumberdaya', views.readPesanan, name='ReadPesananSumberDaya'),
    path('readpesanansumberdaya/detail/<int:idPesanan>', views.detailPesanan, name='DetailPesanan'),
    path('readpesanansumberdaya/riwayatstatus/<int:idPesanan>',views.riwayatStatus,name='RiwayatStatus'),
    path('readpesanansumberdaya/updatepesanan/<int:idPesanan>', views.updatePesanan, name='UpdatePesanan'),
    path('SupplierReadPesanan',views.SupplierReadPesanan,name='SupplierReadPesanan'),
    path('SupplierReadPesanan/detail/<int:idPesanan>',views.detailPesananSupplier,name='DetailPesananSupplier'),
    path('SupplierReadPesanan/riwayatstatus/<int:idPesanan>',views.riwayatStatusSupplier,name='RiwayatStatusSupplier'),
    path('createstockfaskes',views.createStockFaskes, name='CreateStockFaskes'),
    path('liststockfaskes',views.listStockFaskes, name='ListStockFaskes'),
    path('liststockfaskes/updatestock/<str:kodeFaskes>/<str:namaFaskes>/<str:namaItem>', views.updateStockFaskes, name='UpdateStockFaskes'),
    path('liststockfaskespetugas',views.ListStockFaskesPetugas,name='ListStockFaskesPetugas')
]

trigger3/models.py
from django.db import models

# Create your models here.

trigger3/views.py
from django.shortcuts import render, redirect
from django.db import InternalError, connection
from django.contrib import messages
from datetime import date

# Create your views here.

pesanan_query = []
def createPesananSD(request):
    if request.method == "POST" and request.POST['tombol'] == "choose" :
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT kode
            FROM ITEM_SUMBER_DAYA
            WHERE username_supplier='{request.POST["supplier"]}'
            """)
            row = cursor.fetchall()
            kodeBarang = []
            for i in row:
                kodeBarang.append(i[0])
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT DISTINCT username_supplier
            FROM ITEM_SUMBER_DAYA
            """)
            row = cursor.fetchall()
            result = []
            for i in row:
                result.append(i[0])

        context = {
            "supp":request.POST['supplier'],
            "kodeBarang":kodeBarang,
            "result": result,
            "pesanan_query": pesanan_query
        }
    elif request.method == "POST" and request.POST['tombol'] == "tambah":
        # Mengambil seluruh kode barang yg dimiliki supplier
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT kode
            FROM ITEM_SUMBER_DAYA
            WHERE username_supplier='{request.POST["supplier"]}'
            """)
            row = cursor.fetchall()
            kodeBarang = []
            for i in row:
                kodeBarang.append(i[0])

        # Mengambil seluruh username yang menyediakan item sumber daya
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT DISTINCT username_supplier
            FROM ITEM_SUMBER_DAYA
            """)
            row = cursor.fetchall()
            result = []
            for i in row:
                result.append(i[0])

        # Mengambil nama item berdasarkan kode
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT nama,harga_satuan,username_supplier
            FROM item_sumber_daya
            WHERE kode='{request.POST['kode']}'
            """)
            row = cursor.fetchall()
            
            pesanan_query.append(tuple((len(pesanan_query)+1,row[0][0],row[0][1],request.POST['jumlahBarang'],row[0][2])))
        context = {
            "supp":request.POST['supplier'],
            "kodeBarang":kodeBarang,
            "result": result,
            "pesanan_query": pesanan_query
        }
    elif request.method == "POST" and request.POST['tombol'] == "simpan" :
        # Insert into transaksi_sumber_daya
        today = date.today()
        with connection.cursor() as cursor:
            cursor.execute(f"""
            INSERT INTO TRANSAKSI_SUMBER_DAYA 
            (tanggal,total_berat,total_item) VALUES 
            ('{today}',0.0,0.0)
            """)

        # Take max number from transaksi_sumber_daya
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT MAX(nomor)
            FROM transaksi_sumber_daya
            """)
            maxNumber = cursor.fetchall()

        # Insert Into pesanan_sumber_daya
        with connection.cursor() as cursor:
            cursor.execute(f"""
            INSERT INTO PESANAN_SUMBER_DAYA VALUES
            ('{maxNumber[0][0]}','{request.POST['username']}',0.0)
            """)

        # Insert Into Daftar_Item
        for i in pesanan_query:
            with connection.cursor() as cursor:
                cursor.execute(f"""
                SELECT kode 
                FROM ITEM_SUMBER_DAYA
                WHERE nama='{i[1]}'
                """)
                kode = cursor.fetchall()
            with connection.cursor() as cursor:
                cursor.execute(f"""
                INSERT INTO DAFTAR_ITEM VALUES
                ('{maxNumber[0][0]}',{i[0]},{i[3]},{kode[0][0]},0.0,0.0)
                """)
        dataSupplier = []
        for i in pesanan_query:
            dataSupplier.append(i[4])
        dataSupplier2 = list(set(dataSupplier))
        for i in dataSupplier2:
            with connection.cursor() as cursor:
                cursor.execute(f"""
                INSERT INTO RIWAYAT_STATUS_PESANAN VALUES
                ('REQ-SUP','{maxNumber[0][0]}','{i}','{date.today()}')
                """)
        pesanan_query.clear()

        return redirect("trigger3:ReadPesananSumberDaya")

    # Untuk delete
    elif request.method=="POST" and request.POST['tombol'] != "simpan" and request.POST['tombol'] != "tambah" and request.POST['tombol'] != "choose":
        index = int(request.POST['tombol'])-1
        del pesanan_query[index]

        for i in range(index,len(pesanan_query)):
            dataBaru = (str(i+1),pesanan_query[i][1],pesanan_query[i][2],pesanan_query[i][3])
            pesanan_query[i] = dataBaru
        
        # Mengambil seluruh kode barang yg dimiliki supplier
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT kode
            FROM ITEM_SUMBER_DAYA
            WHERE username_supplier='{request.POST["supplier"]}'
            """)
            row = cursor.fetchall()
            kodeBarang = []
            for i in row:
                kodeBarang.append(i[0])

        # Mengambil seluruh username yang menyediakan item sumber daya
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT DISTINCT username_supplier
            FROM ITEM_SUMBER_DAYA
            """)
            row = cursor.fetchall()
            result = []
            for i in row:
                result.append(i[0])
        context = {
            "supp":request.POST['supplier'],
            "kodeBarang":kodeBarang,
            "result": result,
            "pesanan_query": pesanan_query
        }
    else:
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT DISTINCT username_supplier
            FROM ITEM_SUMBER_DAYA
            """)
            row = cursor.fetchall()
            result = []
            for i in row:
                result.append(i[0])
            context = {
                "result": result,
            }

    return render(request, 'trigger3/CreatePesananSumberDaya.html',context)

def readPesanan(request):
    with connection.cursor() as cursor:
        cursor.execute(f"""
        SELECT DISTINCT TSD.nomor, TSD.tanggal, TSD.total_berat, TSD.total_item, PSD.total_harga
        FROM TRANSAKSI_SUMBER_DAYA TSD, PESANAN_SUMBER_DAYA PSD, RIWAYAT_STATUS_PESANAN RSD
        WHERE PSD.nomor_pesanan=TSD.nomor and PSD.nomor_pesanan = RSD.no_pesanan and 
        PSD.username_admin_satgas='{request.session["username"]}';
        """)
        dataPertama = cursor.fetchall()
        print(dataPertama)
    dataStatus = []
    for i in dataPertama:
        print(i[0])
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT DISTINCT username_supplier 
            FROM riwayat_status_pesanan 
            WHERE no_pesanan = '{i[0]}';
            """)
            row = cursor.fetchall()
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT kode_status_pesanan 
            FROM RIWAYAT_STATUS_PESANAN
            WHERE username_supplier='{row[0][0]}' and no_pesanan = '{i[0]}';
            """)
            row = cursor.fetchall()
            dataStatus.append(row[-1][0])
    result = []
    for i in range(len(dataPertama)):
        hasil = (dataPertama[i][0],dataPertama[i][1],dataPertama[i][2],dataPertama[i][3],dataPertama[i][4],dataStatus[i])
        result.append(hasil)
    context = {
        "result":result
    }
    if request.method=="POST":
        print(request.POST['tombol'])
        with connection.cursor() as cursor:
            cursor.execute(f"""
            DELETE FROM RIWAYAT_STATUS_PESANAN 
            WHERE no_pesanan={request.POST['tombol']}
            """)
        with connection.cursor() as cursor:
            cursor.execute(f"""
            DELETE FROM PESANAN_SUMBER_DAYA
            WHERE nomor_pesanan={request.POST['tombol']}
            """)
        with connection.cursor() as cursor:
            cursor.execute(f"""
            DELETE FROM DAFTAR_ITEM
            WHERE  no_transaksi_sumber_daya={request.POST['tombol']}
            """)
        with connection.cursor() as cursor:
            cursor.execute(f"""
            DELETE FROM TRANSAKSI_SUMBER_DAYA
            WHERE nomor={request.POST['tombol']}
            """)
        return redirect("trigger3:ReadPesananSumberDaya")
        
    return render(request, 'trigger3/ReadPesananSumberDaya.html',context)
    
def detailPesanan(request,idPesanan):
    with connection.cursor() as cursor:
        cursor.execute(f"""
        SELECT TSD.tanggal, PSD.total_harga,DI.no_urut, DI.kode_item_sumber_daya, DI.jumlah_item
        FROM TRANSAKSI_SUMBER_DAYA TSD, DAFTAR_ITEM DI, PESANAN_SUMBER_DAYA PSD
        WHERE PSD.nomor_pesanan = TSD.nomor and TSD.nomor = DI.no_transaksi_sumber_daya AND
        PSD.nomor_pesanan={idPesanan};
        """)
        dataPertama = cursor.fetchall()

    dataKedua = []
    for i in dataPertama:
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT DISTINCT ISD.username_supplier,ISD.nama, ISD.harga_satuan
            FROM ITEM_SUMBER_DAYA ISD, DAFTAR_ITEM DI
            WHERE DI.kode_item_sumber_daya = ISD.kode and DI.kode_item_sumber_daya='{i[3]}';
            """)
            result = cursor.fetchall()
            dataKedua.append(result[0])
    result =[]
    for i in range(len(dataPertama)):
        setup = (dataPertama[i][0],dataPertama[i][2],dataKedua[i][1],dataKedua[i][0],dataKedua[i][2],dataPertama[i][4],dataPertama[i][1])
        result.append(setup)
    context = {
        "idPesanan":idPesanan,

trigger3/templates/trigger3/CreatePesananSumberDaya.html
{% extends 'pengguna/base.html' %}

{% block body %}

<div class="container">
    <form method="POST" action="{% url 'trigger3:CreatePesananSumberDaya' %}" style="margin-top: 30px;">
        {% csrf_token %}
        <div class="form-group">
          <label for="supplier"><strong>Choose Supplier:</strong></label>
          <select class="form-control" id="supplier" name="supplier">
              <option value=""></option>
          {% for i in result %}
              <option value={{i}} >{{i}}</option>
          {% endfor %}
          </select>
        </div>
        <button type="submit" class="btn btn-dark" name="tombol" value="choose">Choose</button>
    </form>
    <hr>
    <form method="POST" action="{% url 'trigger3:CreatePesananSumberDaya' %}">
        {% csrf_token %}
        <div class="form-group">
          <label><strong>Your Supplier: </strong></label>
          <input type="text" class="form-control" name="supplier" value={{supp}} readonly>
        </div>
        <div class="form-group">
          <label for="kode"><strong>Kode Item:</strong></label>
          <select class="form-control" id="kode" name="kode">
              {% for i in kodeBarang %}
              <option value={{i}}>{{i}}</option>
              {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label ><strong>Jumlah Item: </strong></label>
          <input class="form-control" type="text" name="jumlahBarang" required>
        </div>
        <button type="submit" class="btn btn-dark" name="tombol" value="tambah">Tambah</button>
    </form>
    <hr>
    <form action="{% url 'trigger3:CreatePesananSumberDaya' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="kode"><strong>Admin Satgas:</strong></label>
          <input type="text" class="form-control" name="username" value={{ request.session.username }} readonly>
        </div>
        <div class="form-group">
          <label><strong>Your Supplier: </strong></label>
          <input type="text"  class="form-control" name="supplier" value={{supp}} readonly>
        </div>

        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">No Urut</th>
                <th scope="col">Item</th>
                <th scope="col">Harga Satuan</th>
                <th scope="col">Jumlah Item</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for i in pesanan_query %}
              <tr>
                <th scope="row">{{i.0}}</th>
                <td>{{i.1}}</td>
                <td>{{i.2}}</td>
                <td>{{i.3}}</td>
                <td><button class="btn btn-danger"  type="submit" name="tombol" value={{i.0}}>delete</button></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <button type="submit" class="btn btn-dark" name="tombol" value="simpan">Simpan</button>
    </form>

</div>

{% endblock body %}

trigger3/templates/trigger3/CreateStockFaskes.html
{% extends 'pengguna/base.html' %}

{% block body %}
<div class="container">
    <h1>FORM TAMBAH STOCK FASKES</h1>
    <form method="POST" action="{% url 'trigger3:CreateStockFaskes' %}">
        {% csrf_token %}
        <div class="form-group">
            <label><strong>Kode Faskes: </strong></label>
            <select class="form-control" id="kode" name="kode">
                <option value=""></option>
            {% for i in kodeFaskes %}
                <option value="{{i.0}}" >{{i.0}}</option>
            {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-dark" name="tombol" value="choose">Choose</button>
    </form>
    <form method="POST" action="{% url 'trigger3:CreateStockFaskes' %}">
        {% csrf_token %}
        <div class="form-group">
            <label><strong>Your Supplier: </strong></label>
            <input type="text" class="form-control" name="kodeFaskesPilihan" value={{kodeFaskesPilihan}} readonly>
        </div>
        <div class="form-group">
            <label for="kode"><strong>Kode Item:</strong></label>
            <select id="kodeItem" class="form-control" name="kodeItem">
                {% for i in kodeItem %}
                <option value={{i.0}}>{{i.0}}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-dark" name="tombol" value="choose2">Choose</button>
    </form>
    <hr>
    <form method="POST" action="{% url 'trigger3:CreateStockFaskes' %}">
        {% csrf_token %}
        <div class="form-group">
            <label>Kode Faskes: </label>
            <input class = "form-control" type="text" name="kodeFaskesPilihan" value={{kodeFaskesPilihan}} readonly>
            <label>Kode Item: </label>
            <input class = "form-control" type="text" name="kodeItem2" value={{kodeItem2}} readonly>
            <label for="">Item Sumber Daya: </label>
            <input class = "form-control" type="text" name="namaItem" value={{namaItem.0.0}} readonly>
            <label for="">Jumlah: </label>
            <input class = "form-control" type="text" name="jumlahBarang" required>    

        </div>
        <button type="submit" name="tombol" value="simpan">SIMPAN</button>
    </form>
</div>
{% endblock body %}

trigger3/templates/trigger3/DetailPesananSupplier.html
{% extends 'pengguna/base.html' %}

{% block body %}
<div class="container-xl">
    <h1 style="text-align: center;">DATA PESANAN SUMBER DAYA</h1>
    
    <p><strong>Nomor Transaksi:</strong> {{idPesanan}}</p>
    <p><strong>Petugas:</strong>{{admin_satgas}}</p>
    <p><strong>Tanggal:</strong> {{result.0.0}}</p>
    <p><strong>Daftar Pesanan Item:</strong> </p>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No Urut</th>
            <th scope="col">Nama Item</th>
            <th scope="col">Supplier</th>
            <th scope="col">Harga Satuan</th>
            <th scope="col">Jumlah Item</th>
          </tr>
        </thead>
        <tbody>
            {% for i in result %}
            <tr>
              <th scope="row">{{i.1}}</th>
              <td>{{i.2}}</td>
              <td>{{i.3}}</td>
              <td>{{i.4}}</td>
              <td>{{i.5}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p><strong>Total Harga:</strong> {{result.0.6}}</p>
    <a class="btn btn-primary" href="{% url 'trigger3:SupplierReadPesanan'%}">Kembali</a><br>
</div>
{% endblock body %}

trigger3/templates/trigger3/ListStockFakses.html
{% extends 'pengguna/base.html' %}

{% block body %}
<div class="container">
    <h1>List Stok Fasilitas Kesehatan</h1>
    <form action="{% url 'trigger3:ListStockFaskes' %}" method="POST">
        {% csrf_token %}
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Kode Faskes</th>
                <th scope="col">Nama Faskes</th>
                <th scope="col">Item Sumber Daya</th>
                <th scope="col">Jumlah</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for i in result %}
                <tr>
                  <th scope="row">{{i.0}}</th>
                  <td>{{i.1}}</td>
                  <td>{{i.2}}</td>
                  <td>{{i.3}}</td>
                  <td style="text-align: center;">
                      <button class="btn btn-primary"  type="submit" name="tombol" value="{{i.0}} {{i.2}}">delete</button><br>
                      <a class="btn btn-primary" href="{% url 'trigger3:UpdateStockFaskes' i.0 i.1 i.2 %}">update</a><br>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
</div>
{% endblock body %}

trigger3/templates/trigger3/ReadPesananSumberDaya.html
{% extends 'pengguna/base.html' %}

{% block body %}
<div class="container-xl">
    <h1 style="text-align: center;">LIST PESANAN SUMBER DAYA</h1>
    <form action="{% url 'trigger3:ReadPesananSumberDaya' %}" method="POST">
        {% csrf_token %}
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">No Transaksi</th>
                <th scope="col">Petugas Satgas</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Total Berat</th>
                <th scope="col">Total Item</th>
                <th scope="col">Total Harga</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for i in result %}
                <tr>
                  <th scope="row">{{i.0}}</th>
                  <td>{{ request.session.username }}</td>
                  <td>{{i.1}}</td>
                  <td>{{i.2}}</td>
                  <td>{{i.3}}</td>
                  <td>{{i.4}}</td>
                  <td>{{i.5}}</td>
                  <td style="text-align: center;">
                    {% if i.5 == 'REQ-SUP' %} 
                      <button class="btn btn-danger"  type="submit" name="tombol" value={{i.0}}>delete</button><br>
                      <a style="margin-top: 4px;" class="btn btn-primary" href="{% url 'trigger3:UpdatePesanan' i.0 %}">update</a><br>
                    {% endif %}
                      <a style="margin-top: 4px;" class="btn btn-primary" href="{% url 'trigger3:DetailPesanan' i.0 %}">Detail</a><br>
                      <a style="margin-top: 4px;" class="btn btn-primary" href="{% url 'trigger3:RiwayatStatus' i.0 %}">Riwayat Status</button>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
</div>
{% endblock body %}

trigger3/templates/trigger3/RiwayatStatusSupplier.html
{% extends 'pengguna/base.html' %}

{% block body %}
<div class="container-xl">
    <h2 style="text-align: center;">RIWAYAT STATUS PESANAN SUMBER DAYA</h2>
    <p><strong>Nomor transaksi:</strong> {{id}} </p>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Kode Status</th>
            <th scope="col">Status</th>
            <th scope="col">Username Supplier</th>
            <th scope="col">Tanggal Persetujuan</th>
          </tr>
        </thead>
        <tbody>
            {% for i in result %}
            <tr>
              <th scope="row">{{i.0}}</th>
              <td>{{i.1}}</td>
              <td>{{i.2}}</td>
              <td>{{i.3}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-primary" href="{% url 'trigger3:SupplierReadPesanan'%}">Kembali</a><br>
</div>
{% endblock body %}

trigger3/templates/trigger3/SupplierReadPesanan.html
{% extends 'pengguna/base.html' %}

{% block body %}
<div class="container-xl">
    <h1 style="text-align: center;">LIST PESANAN SUMBER DAYA</h1>
    <form action="{% url 'trigger3:SupplierReadPesanan' %}" method="POST">
        {% csrf_token %}
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">No Transaksi</th>
                <th scope="col">Petugas Satgas</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Total Berat</th>
                <th scope="col">Total Item</th>
                <th scope="col">Total Harga</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for i in result %}
                <tr>
                  <th scope="row">{{i.0}}</th>
                  <td>{{i.1}}</td>
                  <td>{{i.2}}</td>
                  <td>{{i.3}}</td>
                  <td>{{i.4}}</td>
                  <td>{{i.5}}</td>
                  <td>{{i.6}}</td>
                  <td style="text-align: center;">
                    <a class="btn btn-primary" href="{% url 'trigger3:DetailPesananSupplier' i.0 %}">Detail</a><br>
                    <a style="margin-top: 4px;" class="btn btn-primary" href="{% url 'trigger3:RiwayatStatusSupplier' i.0 %}">Riwayat Status</a><br>
                    {% if i.6 == 'REQ-SUP' %} 
                        <button class="btn btn-danger" type="submit" name="tombol" value="reject {{i.0}}">Reject</button><br>
                        <button style="margin-top: 4px;" class="btn btn-primary" type="submit" name="tombol" value="proses {{i.0}}">Process</button><br>
                    {% elif i.6 == 'PRO-SUP' %}
                        <button style="margin-top: 4px;" class="btn btn-primary" type="submit" name="tombol" value="selesai {{i.0}}">Selesai</button><br>
                        <button style="margin-top: 4px;" class="btn btn-primary" type="submit" name="tombol" value="masalah {{i.0}}">Selesai Dengan Masalah</button><br>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
</div>
{% endblock body %}

trigger3/templates/trigger3/UpdatePesanan.html
{% extends 'pengguna/base.html' %}

{% block body %}

<div class="container-xl">
    <h2 style="text-align: center;">FORM UBAH PESANAN SUMBER DAYA</h2>
    {% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}
    <p><strong>Nomor Transaksi: </strong> {{id}}</p>
    <p><strong>Petugas: </strong> {{request.session.username}}</p>
    <form method="POST" action="{% url 'trigger3:UpdatePesanan' id %}">
        {% csrf_token %}
        <label for="supplier">Choose Supplier:</label>
        <select id="supplier" name="supplier">
            <option value=""></option>
        {% for i in allSupplier %}
            <option value={{i}} >{{i}}</option>
        {% endfor %}
        </select>
        <button type="submit" name="tombol" value="choose">Choose</button>
    </form>
    <hr>
    <form method="POST" action="{% url 'trigger3:UpdatePesanan' id %}">
        {% csrf_token %}
        <label>Your Supplier: </label>
        <input type="text" name="supplier" value={{supp}} readonly>
        <label for="kode">Kode Item:</label>
        <select id="kode" name="kode">
            {% for i in kodeBarang %}
            <option value={{i}}>{{i}}</option>
            {% endfor %}
        </select>
        <label >Jumlah Item: </label>
        <input type="text" name="jumlahBarang" required>
        <button type="submit" name="tombol" value="tambah">Tambah</button>
    </form>
    <hr>
    <form action="{% url 'trigger3:UpdatePesanan' id %}" method="POST">
        {% csrf_token %}
        <label for="kode">Admin Satgas:</label>
        <input type="text" name="username" value={{ request.session.username }} readonly>

        <label>Your Supplier: </label>
        <input type="text" name="supplier" value={{supp}} readonly>

        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">No Urut</th>
                <th scope="col">Item</th>
                <th scope="col">Harga Satuan</th>
                <th scope="col">Jumlah Item</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for i in pesanan_query %}
              <tr>
                <th scope="row">{{i.0}}</th>
                <td>{{i.1}}</td>
                <td>{{i.2}}</td>
                <td>{{i.3}}</td>
                <td><button  type="submit" name="tombol" value={{i.0}}>delete</button></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <button type="submit" name="tombol" value="simpan">Simpan</button>
    </form>
</div>
{% endblock body %}